#!/bin/bash
#set -e
##################################################################################################################
# Author 	: Erik Dubois
# Website   : https://www.erikdubois.be
# Website   : https://www.alci.online
# Website	: https://www.arcolinux.info
# Website	: https://www.arcolinux.com
# Website	: https://www.arcolinuxd.com
# Website	: https://www.arcolinuxb.com
# Website	: https://www.arcolinuxiso.com
# Website	: https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
#tput setaf 0 = black 
#tput setaf 1 = red 
#tput setaf 2 = green
#tput setaf 3 = yellow 
#tput setaf 4 = dark blue 
#tput setaf 5 = purple
#tput setaf 6 = cyan 
#tput setaf 7 = gray 
#tput setaf 8 = light blue
##################################################################################################################
tput setaf 1
echo "##################################################################################"
echo "Skelll is DIRTY way to install everything you need"
echo
echo "It makes it easy to get the configurations in"
echo "and you do not care if you CAN NOT REMOVE them later"
echo
echo "It is DIRTY copy/paste of a lot of configuration files to"
echo "start testing and developing faster"
echo
echo "BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE"
echo "Read this script and test on a virtual machine first"
echo "##################################################################################"
tput sgr0
echo
echo "Can we copy/paste ALL THE CONTENT over - WE WILL OVERWRITE ALL YOUR FILES?"
echo "Only the .config folder will get a backup"
echo
echo "Y/N ???"
echo "##################################################################################"
read response

if [[ "$response" == [yY] ]]; then

	time=$(date +%Y.%m.%d-%H.%M.%S)
	if [ ! -d ~/.config ]; then
		mkdir ~/.config
	fi
	echo
	echo "##################################################################################"
	echo "Making a backup of your .config folder to ~/.config-backup-"$time
	echo "The bigger the .config folder the longer the backup takes"
	echo "Be patient"
	echo "##################################################################################"
	echo

	cp -Rf ~/.config ~/.config-backup-$time

	echo
	echo "##################################################################################"
	echo "Now we overwrite ALL YOUR FILES"
	echo "The larger the content the longer it takes"
	echo "Be patient"
	echo "##################################################################################"
	echo

	sudo cp -rv /arco/etc/modprobe.d /etc/
	echo
	echo "##################################################################################"
	echo
	sudo cp -rv /arco/etc/pacman.d/ /etc/
	echo
	echo "##################################################################################"
	echo	
	sudo cp -rv /arco/etc/samba/ /etc/
	echo
	echo "##################################################################################"
	echo	
	sudo cp -rv /arco/etc/X11/ /etc/
	echo
	echo "##################################################################################"
	echo	
	cp -rv /arco/etc/skel/. $HOME
	echo
	echo "##################################################################################"
	echo	
	sudo cp -rv /arco/usr/* /usr
	echo
	echo "Installing software"
	sudo pacman -S meld --noconfirm --needed
	sudo pacman -S arc-gtk-theme --noconfirm --needed
	sudo pacman -S papirus-icon-theme --noconfirm --needed
	sudo pacman -S sardi-icons --noconfirm --needed
	sudo pacman -S vimix-cursors --noconfirm --needed
	sudo pacman -S archlinux-logout-git --noconfirm --needed
	sudo pacman -S arcolinux-wallpapers-git --noconfirm --needed
	sudo pacman -S rxvt-unicode --noconfirm --needed
	sudo pacman -S sublime-text-4 --noconfirm --needed
	sudo pacman -S ttf-droid --noconfirm --needed
	sudo pacman -S dmenu --noconfirm --needed
	sudo pacman -S ripgrep --noconfirm --needed
	sudo pacman -S variety --noconfirm --needed
	echo
	echo
	tput setaf 1
  	echo "##################################################################################"
	echo "###################                   DONE                    ####################"
	echo "##################################################################################"
	tput sgr0
else
  	echo
  	tput setaf 1
  	echo "##################################################################################"
  	echo "NOTHING has been changed."
  	echo "##################################################################################"
  	tput sgr0
  	echo
fi
